set_num_hitboxes(AT_EXPLOSION, 1);

set_hitbox_value(AT_EXPLOSION, 1, HG_WINDOW, 1);
set_hitbox_value(AT_EXPLOSION, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXPLOSION, 1, HG_LIFETIME, 6);
set_hitbox_value(AT_EXPLOSION, 1, HG_WIDTH, 90);
set_hitbox_value(AT_EXPLOSION, 1, HG_HEIGHT, 90);
set_hitbox_value(AT_EXPLOSION, 1, HG_PRIORITY, 5);
set_hitbox_value(AT_EXPLOSION, 1, HG_DAMAGE, 7);
set_hitbox_value(AT_EXPLOSION, 1, HG_SHAPE, 0);
set_hitbox_value(AT_EXPLOSION, 1, HG_ANGLE, 45);
set_hitbox_value(AT_EXPLOSION, 1, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXPLOSION, 1, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXPLOSION, 1, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_EXPLOSION, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXPLOSION, 1, HG_HITPAUSE_SCALING, .3);
set_hitbox_value(AT_EXPLOSION, 1, HG_EXTRA_CAMERA_SHAKE, 1);
set_hitbox_value(AT_EXPLOSION, 1, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXPLOSION, 1, HG_PROJECTILE_ANIM_SPEED, 0.4);
set_hitbox_value(AT_EXPLOSION, 1, HG_HIT_LOCKOUT, 6);